# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=batchforge
quarkus.datasource.password=batchforge
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/batchforge

# Flyway
quarkus.flyway.migrate-at-start=true

# Redis
quarkus.redis.hosts=redis://localhost:6379

# BatchForge
batchforge.jobs-dir=jobs
